### ISSUE TITLE
Daily Note hotkeys

### ISSUE THREAD

**Issue by nucspl** [Ebonsignori/obsidian-auto-journal#1]
Hello! Could a copy of these navigational hotkeys from Daily Notes core plugin be made?

![image](https://github.com/Ebonsignori/obsidian-auto-journal/assets/80261260/f9a88015-c7dc-4e8e-a1c1-795da934c3c9)

The problem with the Daily Notes hotkeys is that it doesn't recognize notes with anything appended past its given format. Let's say a filename format is set as `YYMMDD -`, adding anything after the dash (`230913 - I am an entry!`) will cause the note to no longer be recognized, and is skipped over when opening next/previous daily notes. The filename format doesn't support wildcards.

And using the today's daily note hotkey will recognize notes _only_ in the specified directory (`📒 Diurna/230913 -`), and will make a new one in it even if there's already one with the same filename in a sub-directory (`📒 Diurna/2023/September/230913 -`).

This plugin is so close to implementing a fully-fledged Logseq-like journaling experience, all that's needed now are working navigational shortcuts!

**Comment by Ebonsignori** [comment]
Good idea! I'll look into adding hotkeys over the weekend.

> And using the today's daily note hotkey will recognize notes only in the specified directory (📒 Diurna/230913 -), and will make a new one in it even if there's already one with the same filename in a sub-directory (📒 Diurna/2023/September/230913 -).

I ran into something similar and have a link to the current daily note on my dashboard that is always open using https://github.com/mirnovov/obsidian-homepage

If you want to use it in the meantime, it will always link to today's daily note (though you may need to alter what's passed to .format() to match the format you're using for your daily notes),

<details>
<summary>Dataview JS codeblock</summary>

```
```dataviewjs
const today = moment()
const folder = `Journal/${today.format("yyyy")}/${today.format("MMMM")}`

function getTodaysJournalLink() {
	const dayFiles = app.vault.getFiles().filter(file => file.parent.path == folder)
	
	let link
	for (const file of dayFiles) {
	  if (file.name.split('-')?.[0]?.trim() === today.format("DD")) {  
	    link = app.fileManager.generateMarkdownLink(
			file,
			file.path,
			undefined,
			truncate(file.name.slice(0, -3), 40),
		);
	    break
	  }
	}
	return link
}


function truncate(str, n){
    if (!str) {
      return ""
    }
    return (str.length > n) ?   str.substr(0, n-5) + '&hellip;' : str;
};

async function main() {
	let link = getTodaysJournalLink()
	if (!link) {
	  console.log("manually triggering auto-journal")
  app.commands.executeCommandById('auto-journal:manually-trigger');
      // Wait for the new file to be created
	  await new Promise((resolve) => setTimeout(resolve, 1000))
	  link = getTodaysJournalLink()
	}
	
	dv.span(`**${moment().format("MMMM")}** ✍️:  ${link}`)
	
	dv.container.classList.add("dashboard-heading")
}

main()
```
</details>

It will link to the daily note even after you alter the title of that note, as long as the `date - ` prefix remains

**Comment by Ebonsignori** [comment]
@nucspl added commands & navigation buttons in https://github.com/Ebonsignori/obsidian-auto-journal/releases/tag/1.3.0 

Let me know if you run into any trouble using them!

**Comment by nucspl** [comment]
The navigation works great, thank you for this addition! :)

I've had no hiccups with it so far, though I did encounter an oddity that may be a potential bug: The last days of the past two months (September 30 and October 31) weren't made/backfilled, so its absence interrupted navigation.

With that in mind, it would be nice to have missing previous days be backfilled and future days be pre-made when navigated to, but that's an enhancement for another time.

**Comment by Ebonsignori** [comment]
> I've had no hiccups with it so far, though I did encounter an oddity that may be a potential bug: The last days of the past two months (September 30 and October 31) weren't made/backfilled, so its absence interrupted navigation.

Did this happen before or after I added the new navigation (in ~1.3.x)?

I fixed a bug for yearly backfilling that was failing to backfill the last few days of months with less days than the current month, but might have missed another if you're still running into it. 

> it would be nice to have missing previous days be backfilled and future days be pre-made when navigated to

It would be! Went ahead and added this behavior in [1.3.3](https://github.com/Ebonsignori/obsidian-auto-journal/releases/tag/1.3.3)

**Comment by nucspl** [comment]
>Did this happen before or after I added the new navigation (in ~1.3.x)?

I believe it was from before (1.2.x), I only updated recently so those days were already missed. But with 1.3.3, it shouldn't be much of an issue now if it's still present, though I'll still keep an eye out.

Speaking of which, the new feature is nifty! It really completes the plugin! Didn't expect it to be added in so quickly, cheers!
